version: 0.2

phases:
  install:
    commands:
      - yum install git  # Install Git for Amazon Linux image
      - pip install awscli

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR

      # Set Internal Field Separator to newline
      - IFS=$'\n'

      # Extract changed files from commit messages
      - changed_files=($(git diff --name-only HEAD^..HEAD))

      # Reset Internal Field Separator
      - unset IFS

      # Iterate through changed files
      - |
        for changed_file in "${changed_files[@]}"; do
          # Extract function name from commit message
          function_name=$(git log -1 --pretty=%s | grep -oP "update function: \K\S+" | head -n 1)

          # Ensure the commit message contains "update function:" and function name is extracted
          if [[ $function_name == "update function:"* && -n $function_name ]]; then
            zip_file_path="${function_name}.zip"

            # Zip only the changed file
            zip -r "$zip_file_path" "$changed_file"

            # Update Lambda function with the new code
            aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://$zip_file_path"
          fi
        done

artifacts:
  discard-paths: yes
