version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git diff --name-only $CODEBUILD_SOURCE_VERSION HEAD~1 > changed_files.txt
      - python conditional_update.py


