version: 0.2

phases:
  install:
    commands:
      - yum install git  # Install Git for Amazon Linux image
      - pip install awscli
      - git config --global user.email "arjun.betageri@live.com"
      - git config --global user.name "ar7u4"
      - git config --global credential.helper '!f() { echo "password=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"; }; f'
      - git --version

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - git --version
      - git diff --name-only $CODEBUILD_WEBHOOK_PREV_COMMIT $CODEBUILD_RESOLVED_SOURCE_VERSION
      # Extract changed files from commit messages
      - changed_files=$(git diff --name-only $CODEBUILD_WEBHOOK_PREV_COMMIT $CODEBUILD_RESOLVED_SOURCE_VERSION)

      # Iterate through changed files
      - |
        for changed_file in $changed_files; do
          # Extract function name from commit message
          function_name=$(git log -1 --pretty=%s | grep -oP "update function: \K\S+" | head -n 1)

          # Ensure the commit message contains "update function:" and function name is extracted
          if [[ $function_name == "update function:"* && -n $function_name ]]; then
            # Zip only the changed file
            zip_file_path="${function_name}.zip"
            zip -r "$zip_file_path" "$changed_file"

            # Update Lambda function with the new code
            aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://$zip_file_path"
          fi
        done

artifacts:
  discard-paths: yes
