version: 0.2

phases:
  install:
    commands:
      - yum install git  # Install Git for Amazon Linux image
      - pip install awscli

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR  # Replace with the correct path

      - changed_files=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo "Resolved Source Version: $CODEBUILD_RESOLVED_SOURCE_VERSION"

      - echo "$changed_files" > changed_files.txt

      - IFS=$'\n'  # Set Internal Field Separator to newline
      - extracted_function_names=($(git log -1 --pretty=%s))
      - unset IFS

      # Directly use extracted_function_names for conditional updates
      - |
        for function_name in "${extracted_function_names[@]}"; do
          if [[ $function_name == *"update function:"* ]]; then
            function_name=${function_name:16}  # Extract from commit message
            if grep -q "$function_name" changed_files.txt; then
              zip_file_path="${function_name}.zip"

              # Zip only changed files:
              > "$zip_file_path"  # Clear any existing zip file
              while read -r file; do
                zip -r "$zip_file_path" "$file"
              done < changed_files.txt

              aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://$zip_file_path"
            fi
          fi
        done

artifacts:
  discard-paths: yes
