version: 0.2

phases:
  install:
    commands:
      - pip install awscli

  build:
    commands:
      - changed_files=$(git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo "$changed_files" > changed_files.txt  # Save the changed files to a file

      - extracted_function_names=$(git log -1 --pretty=%s)
      - for function_name in $extracted_function_names; do
          if [[ $function_name == *"update function:"* ]]; then
            function_name=${function_name:16}  # Extract from commit message
            if grep -q "$function_name" changed_files.txt; then
              zip_file_path="${function_name}.zip"
              zip -r "$zip_file_path" "$function_name"  # Zip the Lambda function directory
              aws lambda update-function-code --function-name "$function_name" --zip-file "fileb://$zip_file_path"
            fi
          fi
        done
